name: TS-Playlist
on:
 workflow_dispatch:
  inputs:
    git_token:
      description: 'Enter your GitHub Token'     
      required: true
    tata_mobile:
      description: 'Enter your Tata Sky Mobile Number'
      required: false
    sub_id:
      description: 'Enter your Tata Sky Subscriber ID'
      required: false
    tata_pass:
      description: 'Enter your Tata Sky Password'     
      required: false
    git_mail:
      description: 'Enter your GitHub Mail Address'
      required: true
    git_id:
      description: 'Enter your GitHub ID'
      required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
    - name: Installing Dependencies
      continue-on-error: true
      run: |
            git config --global user.name "${{ github.event.inputs.git_id }}"
            git config --global user.email "${{ github.event.inputs.git_mail }}"
            git clone https://github.com/beatstrick/Beat-TataSky
            cd Beat-TataSky/
            cd code_samples/
            sudo apt install expect -y
            wget https://gist.githubusercontent.com/beatstrick/5f375734631f46c243aea89993495b02/raw/TSlogin.exp
            chmod 777 TSlogin.exp
            sed -i 's/PASSWORD/${{ github.event.inputs.tata_pass }}/g' TSlogin.exp
            sed -i 's/SUB_ID/${{ github.event.inputs.sub_id }}/g' TSlogin.exp
            sed -i 's/MOB_NO/${{ github.event.inputs.tata_mobile }}/g' TSlogin.exp
            ./TSlogin.exp >> /dev/null 2>&1
            touch mytoken.txt
            echo "${{ github.event.inputs.git_token }}" >> mytoken.txt
            gh auth login --with-token < mytoken.txt
            mkdir git-repo/
            cd git-repo/
            touch mytatasky.m3u
            echo "Initial Test" >> mytatasky.m3u
            gh gist create mytatasky.m3u | tee gist_link.txt
            sed -i 's/gist/${{ github.event.inputs.git_token }}@gist/g' gist_link.txt
            gist_url=$(cat gist_link.txt)
            dir="${gist_url##*/}"
            git clone https://github.com/beatstrick/Beat-TataSky
            gh repo create MyTataSky-Daily --private -y || echo "New repo has been created"
            mv ../TSlogin.exp Beat-TataSky/code_samples/
            chmod 755 Beat-TataSky/code_samples/TSlogin.exp
            cd Beat-TataSky/
            mkdir .github
            cd .github
            mkdir workflows
            cd workflows
            wget https://gist.githubusercontent.com/beatstrick/65be3850cc7f34414a4690f84a4cca48/raw/TSDailyWF.yml
            wget https://gist.githubusercontent.com/beatstrick/dc2e47e98799b1b72a9f850bed34cd7d/raw/TSaddon.txt
            export dir=$dir
            export gist_url=$gist_url
            export git_id=${{ github.event.inputs.git_id }}
            export git_token=${{ github.event.inputs.git_token }}
            export git_mail=${{ github.event.inputs.git_mail }}
            cat TSaddon.txt | envsubst >> TSDailyWF.yml
            rm TSaddon.txt
            cd ../..
            rm -rf .git
            cd ..
            git clone https://${{ github.event.inputs.git_token }}@github.com/${{ github.event.inputs.git_id }}/MyTataSky-Daily
            rm -rf MyTataSky-Daily/*
            rm -rf MyTataSky-Daily/.github
            mv Beat-TataSky/* MyTataSky-Daily/
            mv Beat-TataSky/.github MyTataSky-Daily/
            cd MyTataSky-Daily/
            git add .
            git commit --author="BeatsTrick" -m "Update Repo"
            git push


            
            
            
            

            
